@startsalt PatientScanlines_Solitaire_AppLayout
title General App Layout
!theme vibrant
skinparam linetype polyline

' this is the footer containing license information, should only need to be included one but may have to re-paste on multi-page documents
center footer [[https://creativecommons.org/licenses/by-sa/4.0/ <img:https://licensebuttons.net/l/by-sa/4.0/88x31.png>]] [[https://www.gnu.org/licenses/gpl-3.0.en.html <img:https://www.gnu.org/graphics/gplv3-88x31.png>]] \n This work is licensed under a [[https://creativecommons.org/licenses/by-sa/4.0/ CC BY-SA 4.0]],\n code & software examples licensed under [[https://www.gnu.org/licenses/gpl-3.0.en.html GNU GPLv3]].

{"Layout"
{SI
{^"Nav/App-Bar"
    {T
        MainMenu <&star> | Favourites <&check> | Settings <&cog>
    }
}
...|...
{
    {^"Games"
    Pick a Game
    ===
    {
        **Minesweeper** |
        <<minesweeper 
        XXXXXXX
        X...X.X
        X..X..X
        X.XXX.X
        XXXXXXX
        XXXXXXX
        X.XXX.X
        XXXXXXX
        >>
    }
    {T
        +Easy
        +Medium
        +Hard
        +Endless
    }
    ---
    {
        **Solitaire** |
        <<solitaire 
        XXXXXXX
        XX...XX
        XX...XX
        X..X..X
        X..X..X
        XX...XX
        XX...XX
        XXXXXXX
        >>
    }
    {T
        +Easy
        ++Klondike
        ++Vegas
        ++Free-Cell
        +Hard
        ++Fourty Thieves
        ++Algerian
        ++Spider
    }
    ---
    {
        **Block Game** |
        <<blockGame 
        XXXXXXX
        X...X.X
        XX.XX.X
        XXX.XXX
        XXX..XX
        XX...XX
        XXX.XXX
        XXXXXXX
        >>
    }
    {T
        +Legacy Endless
        +Zen MonoSpeed
        +Custom %
    }
    ---
    {
        **Snake**
    }
    {T
        +Retro
        +Scaling
    }
    ---
} | {^"Settings"
    Settings
    {
        {^**User Settings**
            [X] <color:Blue> __Theme__
        }
        {^**System Settings**
            [X] Keep Score
            [ ] Cloud Sync <&cloud>| <color:Blue> Setup?
        }
    }
}
}
}
}
@endsalt